const words = [
    // МОБЫ
    { word: "крипер",     category: "Мобы" },
    { word: "зомби",      category: "Мобы" },
    { word: "скелет",     category: "Мобы" },
    { word: "паук",       category: "Мобы" },
    { word: "эндермен",   category: "Мобы" },
    { word: "свинья",     category: "Мобы" },
    { word: "корова",     category: "Мобы" },
    { word: "овца",       category: "Мобы" },
    { word: "курица",     category: "Мобы" },
    { word: "лошадь",     category: "Мобы" },
    { word: "волк",       category: "Мобы" },
    { word: "кот",        category: "Мобы" },
    { word: "гаст",       category: "Мобы" },
    { word: "слизень",    category: "Мобы" },
    { word: "ифрит",      category: "Мобы" },
    { word: "фантом",     category: "Мобы" },
    { word: "утопленник", category: "Мобы" },
    { word: "пиглин",     category: "Мобы" },
    { word: "страж",      category: "Мобы" },
    { word: "дракон",     category: "Мобы" },
    { word: "иссушитель", category: "Мобы" },

    // БЛОКИ
    { word: "камень",     category: "Блоки" },
    { word: "земля",      category: "Блоки" },
    { word: "песок",      category: "Блоки" },
    { word: "гравий",     category: "Блоки" },
    { word: "дерево",     category: "Блоки" },
    { word: "доски",      category: "Блоки" },
    { word: "булыжник",   category: "Блоки" },
    { word: "обсидиан",   category: "Блоки" },
    { word: "алмаз",      category: "Блоки" },
    { word: "изумруд",    category: "Блоки" },
    { word: "золото",     category: "Блоки" },
    { word: "железо",     category: "Блоки" },
    { word: "редстоун",   category: "Блоки" },
    { word: "лазурит",    category: "Блоки" },
    { word: "кварц",      category: "Блоки" },
    { word: "нефрит",     category: "Блоки" },
    { word: "бедрок",     category: "Блоки" },

    // ПРЕДМЕТЫ
    { word: "кирка",      category: "Предметы" },
    { word: "меч",        category: "Предметы" },
    { word: "топор",      category: "Предметы" },
    { word: "лопата",     category: "Предметы" },
    { word: "мотыга",     category: "Предметы" },
    { word: "лук",        category: "Предметы" },
    { word: "стрела",     category: "Предметы" },
    { word: "ведро",      category: "Предметы" },
    { word: "факел",      category: "Предметы" },
    { word: "верстак",    category: "Предметы" },
    { word: "печь",       category: "Предметы" },
    { word: "сундук",     category: "Предметы" },
    { word: "кровать",    category: "Предметы" },
    { word: "компас",     category: "Предметы" },
    { word: "карта",      category: "Предметы" },
    { word: "часы",       category: "Предметы" },
    { word: "удочка",     category: "Предметы" },
    { word: "ножницы",    category: "Предметы" },

    // МЕСТА
    { word: "деревня",    category: "Места" },
    { word: "шахта",      category: "Места" },
    { word: "пещера",     category: "Места" },
    { word: "портал",     category: "Места" },
    { word: "край",       category: "Места" },
    { word: "нижний мир", category: "Места" },
    { word: "биом",       category: "Места" },
    { word: "пустыня",    category: "Места" },
    { word: "тайга",      category: "Места" },
    { word: "джунгли",    category: "Места" },
    { word: "болото",     category: "Места" },
    { word: "океан",      category: "Места" },

    // ЕДА
    { word: "яблоко",     category: "Еда" },
    { word: "хлеб",       category: "Еда" },
    { word: "морковь",    category: "Еда" },
    { word: "картофель",  category: "Еда" },
    { word: "свекла",     category: "Еда" },
    { word: "арбуз",      category: "Еда" },
    { word: "тыква",      category: "Еда" },
    { word: "гриб",       category: "Еда" },
    { word: "печенье",    category: "Еда" },
    { word: "торт",       category: "Еда" },

    // МЕХАНИЗМЫ
    { word: "зачарование",      category: "Механики" },
    { word: "зелье",            category: "Механики" },
    { word: "вагонетка",        category: "Механики" },
    { word: "рельсы",           category: "Механики" },
    { word: "маяк",             category: "Механики" },
    { word: "наковальня",       category: "Механики" },
    { word: "динамит",          category: "Механики" },
    { word: "поршень",          category: "Механики" },
    { word: "наблюдатель",      category: "Механики" },
    { word: "повторитель",      category: "Механики" },
    { word: "компаратор",       category: "Механики" }
];

const maxMistakes = 6;
const alphabet = "абвгдеёжзийклмнопрстуфхцчшщъыьэюя";